name: Keepalive Workflows
description: |
  Automatically generates activity on the default git branch when no activity
  has been recorded for a longer period of time. This avoids workflows to be
  disabled by GitHub after 60 days of inactivity. By default, this action uses a
  hidden file within the `.github` directory whenever git activity is required.
  The path to that file can be controlled through the `liveness` input.
author: Emmanuel Frecon <efrecon+github@gmail.com>
branding:
  icon: activity
  color: green

inputs:
  timeout:
    description: |
      The number of seconds of inactivity on the default branch before
      generating a commit. The default is 41 days, i.e. just above 2/3 of the
      GitHub inactivity trigger.
    required: false
    default: 3542400
  liveness:
    description: |
      Path (relative to repository) to a file where a marker will be
      put/actualised whenever activity is required to be generated on the
      repository. This file is used whenever the `marker` is empty, i.e. in most
      cases.
    default: '.github/.github_liveness.txt'
  token:
    description: |
      GitHub token. The default is the default github token, which is enough to
      perform a git commit onto the default file from `liveness`. If you want to
      use a workflow such as the activity marker instead, pass a token with
      enough privileges to change the content of workflows. In that case, you
      might want to use the current workflow, i.e. the workflow running the
      action available at `github.workflow`.
    required: false
    default: "${{ github.token }}"
  options:
    description: |
      Additional options to `activity.sh` script, e.g. -v to print out
      additional verbose information. This is a semi-internal input and should
      only be used for debugging.
    required: false
    default: ""
  marker:
    description: |
      Name of workflow to use for activity marker. The default is to have an
      empty marker, in which case this action will use the file from `liveness`
      when it is necessary to generate activity on the repository to keep it
      alive. Instead of an empty marker, you can pass the name of a workflow
      instead, e.g. the value of `github.workflow`, in which case the marker
      will be added/updated at the end of the workflow that called the action.
      This requires a GitHub token that is able to change workflows, which the
      default `github.token` cannot do.
    required: false
    default: ""

runs:
  using: composite
  steps:
    -
      name: Minimal Checkout
      id: checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        fetch-depth: 1
    -
      name: Activity Keeper
      id: activator
      shell: bash
      env:
        ACTIVITY_GHAPI: ${{ github.api_url }}
      run: |
        ${{ github.action_path }}/activity.sh \
          -t '${{ inputs.token }}' \
          -m '${{ inputs.timeout }}' \
          -l '${{ inputs.liveness }}' \
          ${{ inputs.options }} \
          -- \
            '${{ inputs.marker }}' \
            '${{ github.repository }}'
